# Dependencies
markdown:            redcarpet
highlighter:         'pygments'
gems:                [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Pietro Menna
tagline:             'Home page'
description:         'Pietro Menna`s space in the Internet'
url:                 http://pietromenna.github.io
baseurl:             /
paginate:            3

# About/contact
author:
  name:              Pietro Menna
  url:               https://twitter.com/pietromenna
  email:             pietro@menna.net.br

# Custom vars
version:             1.0.0

contact:
  GitHub:            'https://github.com/pietromenna'
  Keybase:           'https://keybase.io/pietromenna'
  Twitter:           'https://twitter.com/pietromenna'